//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research
{
    using System;
    using System.Collections.Generic;
    
    public partial class research_application_tb
    {
        public long Id { get; set; }
        public string CustomerName { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string CompanyAddress { get; set; }
        public string Referrals { get; set; }
        public string ReferralsNumber { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string BComany { get; set; }
        public string CustomerTel { get; set; }
        public string TbWriter { get; set; }
        public string PinPai1 { get; set; }
        public string PinPai2 { get; set; }
        public string PinPai3 { get; set; }
        public string Fax { get; set; }
        public string Model { get; set; }
        public Nullable<int> StoreArea { get; set; }
        public Nullable<int> StoreNum { get; set; }
        public string StoreName { get; set; }
        public string BusinessRecords { get; set; }
        public string BrandName { get; set; }
        public string FriendBrand { get; set; }
        public string FriendBrandName { get; set; }
        public Nullable<int> Sales9 { get; set; }
        public Nullable<int> Sales10 { get; set; }
        public Nullable<int> Sales11 { get; set; }
        public Nullable<int> Sales12 { get; set; }
        public Nullable<int> Sales1 { get; set; }
        public Nullable<int> Sales2 { get; set; }
        public string CooperationMode { get; set; }
        public string Coordinate { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string AmountExpected { get; set; }
        public string AgentAdvantages { get; set; }
        public string FranchiseApplication { get; set; }
        public string ProfitForecast { get; set; }
        public string Suggestions { get; set; }
        public byte[] Image { get; set; }
    }
}
