//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class research_application_tb
    {
        //public long Id { get; set; }
        //public string CustomerName { get; set; }
        //public string ContactPerson { get; set; }
        //public string ContactPhone { get; set; }
        //public string CompanyAddress { get; set; }
        //public string Province { get; set; }
        //public string City { get; set; }
        //public byte[] Image { get; set; }
        //public string ImageType { get; set; }
        //public string Remark { get; set; }
        //public string BCompany { get; set; }
    }
}
