//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_City
    {
        public S_City()
        {
            this.S_District = new HashSet<S_District>();
        }
    
        public long CityID { get; set; }
        public string CityName { get; set; }
        public string ZipCode { get; set; }
        public Nullable<long> ProvinceID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual S_Province S_Province { get; set; }
        public virtual ICollection<S_District> S_District { get; set; }
    }
}
