//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Province
    {
        public S_Province()
        {
            this.S_City = new HashSet<S_City>();
        }
    
        //public long ProvinceID { get; set; }
        //public string ProvinceName { get; set; }
        //public Nullable<System.DateTime> DateCreated { get; set; }
        //public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ICollection<S_City> S_City { get; set; }
    }
}
